authors:
  mamadou:
    name: Mahamoudou Sandwidi        # Author name
    description: IT, Networking, Cloud, Software # Author description
    avatar: https://masandwidi.net/my-avatar         # Author avatar
    slug: mahamoudou-sandwidi           # Author profile slug
    url: https://masandwidi.net            # Author website URL